/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SendSelectRouteImport } from './routes/send-select'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as NftsRouteImport } from './routes/nfts'
import { Route as NftRouteImport } from './routes/nft'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SendSelectRoute = SendSelectRouteImport.update({
  id: '/send-select',
  path: '/send-select',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const NftsRoute = NftsRouteImport.update({
  id: '/nfts',
  path: '/nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const NftRoute = NftRouteImport.update({
  id: '/nft',
  path: '/nft',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/buy': typeof BuyRoute
  '/explore': typeof ExploreRoute
  '/nft': typeof NftRoute
  '/nfts': typeof NftsRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/send-select': typeof SendSelectRoute
  '/swap': typeof SwapRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/buy': typeof BuyRoute
  '/explore': typeof ExploreRoute
  '/nft': typeof NftRoute
  '/nfts': typeof NftsRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/send-select': typeof SendSelectRoute
  '/swap': typeof SwapRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/buy': typeof BuyRoute
  '/explore': typeof ExploreRoute
  '/nft': typeof NftRoute
  '/nfts': typeof NftsRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/send-select': typeof SendSelectRoute
  '/swap': typeof SwapRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/buy'
    | '/explore'
    | '/nft'
    | '/nfts'
    | '/receive'
    | '/send'
    | '/send-select'
    | '/swap'
    | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/buy'
    | '/explore'
    | '/nft'
    | '/nfts'
    | '/receive'
    | '/send'
    | '/send-select'
    | '/swap'
    | '/terminal'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/buy'
    | '/explore'
    | '/nft'
    | '/nfts'
    | '/receive'
    | '/send'
    | '/send-select'
    | '/swap'
    | '/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BuyRoute: typeof BuyRoute
  ExploreRoute: typeof ExploreRoute
  NftRoute: typeof NftRoute
  NftsRoute: typeof NftsRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  SendSelectRoute: typeof SendSelectRoute
  SwapRoute: typeof SwapRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-select': {
      id: '/send-select'
      path: '/send-select'
      fullPath: '/send-select'
      preLoaderRoute: typeof SendSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfts': {
      id: '/nfts'
      path: '/nfts'
      fullPath: '/nfts'
      preLoaderRoute: typeof NftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft': {
      id: '/nft'
      path: '/nft'
      fullPath: '/nft'
      preLoaderRoute: typeof NftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BuyRoute: BuyRoute,
  ExploreRoute: ExploreRoute,
  NftRoute: NftRoute,
  NftsRoute: NftsRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  SendSelectRoute: SendSelectRoute,
  SwapRoute: SwapRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
